# Common B3 Tickers (IBOV + Others)
B3_TICKERS = {
    "VALE": "VALE3", "PETROBRAS": "PETR4", "ITAU": "ITUB4", "BRADESCO": "BBDC4", "AMBEV": "ABEV3",
    "BB": "BBAS3", "B3": "B3SA3", "WEG": "WEGE3", "ITAUSA": "ITSA4", "GERDAU": "GGBR4",
    "RENT3": "RENT3", "SUZANO": "SUZB3", "MAGALU": "MGLU3", "LOCALIZA": "RENT3", "HAPVIDA": "HAPV3",
    "RAIA": "RADL3", "TELEFONICA": "VIVT3", "TIM": "TIMS3", "AZUL": "AZUL4", "GOL": "GOLL4",
    "COGNA": "COGN3", "CSN": "CSNA3", "JBS": "JBSS3", "MARFRIG": "MRFG3", "MINERVA": "BEEF3",
    "EMBRAER": "EMBR3", "CCR": "CCRO3", "ELETROBRAS": "ELET3", "SABESP": "SBSP3", "CMIG": "CMIG4",
    "COPEL": "CPLE6", "HYPERA": "HYPE3", "LOJAS RENNER": "LREN3", "NATURA": "NTCO3", "TOTVS": "TOTS3",
    "VIBRA": "VBBR3", "ASSAI": "ASAI3", "CARREFOUR": "CRFB3", "ULTRAPAR": "UGPA3", "EQUATORIAL": "EQTL3",
    "RAIZEN": "RAIZ4", "COSAN": "CSAN3", "PRIO": "PRIO3", "3R": "RRRP3", "PETRORIO": "PRIO3",
    "PETRORECONCAVO": "RECV3", "SANTANDER": "SANB11", "BTG": "BPAC11", "INTER": "INBR32", "NUBANK": "ROXO34"
}
